### ISSUE TITLE
recipe in smp

### ISSUE THREAD

**Issue by quentffr21** [xbony2/AFSU#6]
hello

minecraft 1.7.10
1.2.0a-Mustard
IC2 2.2.658

i can't craft afsu on my server , i see afsu block on output slot but i can't take it 
i got no prob in solo 

thanks

**Comment by xbony2** [comment]
Bleah... that's a weird issue. Have you had any issues with other blocks/items? Testing the AFB would be good. Also, do you have Cauldron/MCPC?

Good to have an excuse to make an update to add the Russian translation in, I must say :P

**Comment by quentffr21** [comment]
hello 
no more issue for me

i have no cauldron/mcpc only forge

thanks

**Comment by master801** [comment]
What was the problem?

**Comment by xbony2** [comment]
I think it wasn't really an issue.

**Comment by quentffr21** [comment]
hello

with the normal version i can craft afb but i can't craft afsu (recipe was correctly displayed but i can't take it, look like recipe only registered client side)

and if i use applied energetic i can't take afb out of my network (that was strange).
i see it on my network (maybe don't like to be stacked)

i will try with a fresh server with only ic2 and afsu to see if i get this issue
i use inventory tweak maybe issue come with it (sync prob)

**Comment by Zarkov2** [comment]
I can confirm this problem still exists using IC2 2.2.722, AFSU 1.2.1a Mustard and Forge 10.13.3.1391.

Unable to craft the AFSU in both AE crafting terminal and vanilla crafting table when playing on a dedicated server. Output shows up but couldn't pick it up (like the recipe isn't registered on the server).

After disconnecting and connecting again to server, I could complete the crafting (only tested in vanilla table).

**Comment by xbony2** [comment]
Dang it, what a weird bug...

**Comment by master801** [comment]
Update IC2-Experimental to at least version "2-2.2.726".

AFSU is not the problem, IC2-Experimental is.

**Comment by Milii20** [comment]
Greetings!, not trying to revive a 6+ years old github, nor i am trying to ask for an update or anything, but since the issue is still happening i figured i would make suggestions to people who want to use the mod:

Latest 1.7.10 ic2 (2-2.2.828-experimental) 
Latest 1.7.10 Forge (10.13.4.14)

What i found out:

1) DO NOT PLACE THE AFB IN AN AE SYSTEM, YOU WONT BE ABLE TO TAKE IT OUT EASILY (dont really know why, but i had to export it using an export bus with a fuzzy card, otherwise can't take it out of the storage from the terminal)
2) In case you have the issue of the recipes, grab the stuff in your inventory, disconect from the server, connect again, use a vanilla workbench and you will be able to craft the AFSU
3) The probable cause is some other mod using an old ic2 api or something, wasnt able to figure it out

**Comment by steampunkerdrink** [comment]
+++ for last comment, i used ME Chest to get it out. Will post MineTweaker 3 script here to replace AFP core on AFPU craft shortly

**Comment by steampunkerdrink** [comment]
`#Fix AFSU Craft by removing AFB core from recipe and adding 2 more iridium plates and u-matter cell


recipes.addShaped(<AFSU:AFSU>,
 [[<IC2:blockElectric:2>, <IC2:itemPartIridium>, <IC2:blockElectric:2>],
 [<IC2:itemPartIridium>, <IC2:itemCellEmpty:3>, <IC2:itemPartIridium>],
 [<IC2:blockElectric:2>, <IC2:itemPartIridium>, <IC2:blockElectric:2>]
 ]);


`
